#ifndef PORT_PROMPT_ART_H
#define PORT_PROMPT_ART_H

namespace prompt_art
{

struct Art
{
    const char* key;
    const char* file;
};

// clang-format off
const Art kArt[] = {
    { "gamecube/a",            "kenney/Nintendo Gamecube/gamecube_button_color_a.png" },
    { "gamecube/b",            "kenney/Nintendo Gamecube/gamecube_button_color_b.png" },
    { "gamecube/back",         "kenney/Nintendo Gamecube/gamecube_button_start.png" },
    { "gamecube/circle",       "kenney/PlayStation Series/playstation_button_color_circle.png" },
    { "gamecube/cross",        "kenney/PlayStation Series/playstation_button_color_cross.png" },
    { "gamecube/down",         "kenney/Nintendo Gamecube/gamecube_dpad_down.png" },
    { "gamecube/east",         "kenney/Nintendo Switch/switch_buttons_right.png" },
    { "gamecube/guide",        "kenney/Generic/generic_button_circle.png" },
    { "gamecube/lb",           "kenney/Nintendo Gamecube/gamecube_trigger_l.png" },
    { "gamecube/left",         "kenney/Nintendo Gamecube/gamecube_dpad_left.png" },
    { "gamecube/ls",           "kenney/Nintendo Gamecube/gamecube_stick.png" },
    { "gamecube/ls_down",      "kenney/Nintendo Gamecube/gamecube_stick_down.png" },
    { "gamecube/ls_left",      "kenney/Nintendo Gamecube/gamecube_stick_left.png" },
    { "gamecube/ls_right",     "kenney/Nintendo Gamecube/gamecube_stick_right.png" },
    { "gamecube/ls_up",        "kenney/Nintendo Gamecube/gamecube_stick_up.png" },
    { "gamecube/lt",           "kenney/Nintendo Gamecube/gamecube_trigger_l.png" },
    { "gamecube/misc1",        "kenney/Nintendo Gamecube/gamecube_button_z.png" },
    { "gamecube/misc2",        "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "gamecube/misc3",        "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "gamecube/misc4",        "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "gamecube/misc5",        "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "gamecube/misc6",        "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "gamecube/north",        "kenney/Nintendo Switch/switch_buttons_up.png" },
    { "gamecube/p1",           "kenney/Xbox Series/xbox_elite_paddle_top_right.png" },
    { "gamecube/p2",           "kenney/Xbox Series/xbox_elite_paddle_top_left.png" },
    { "gamecube/p3",           "kenney/Xbox Series/xbox_elite_paddle_bottom_right.png" },
    { "gamecube/p4",           "kenney/Xbox Series/xbox_elite_paddle_bottom_left.png" },
    { "gamecube/rb",           "kenney/Nintendo Gamecube/gamecube_button_z.png" },
    { "gamecube/right",        "kenney/Nintendo Gamecube/gamecube_dpad_right.png" },
    { "gamecube/rs",           "kenney/Nintendo Gamecube/gamecube_stick_c.png" },
    { "gamecube/rs_down",      "kenney/Nintendo Gamecube/gamecube_stick_c_down.png" },
    { "gamecube/rs_left",      "kenney/Nintendo Gamecube/gamecube_stick_c_left.png" },
    { "gamecube/rs_right",     "kenney/Nintendo Gamecube/gamecube_stick_c_right.png" },
    { "gamecube/rs_up",        "kenney/Nintendo Gamecube/gamecube_stick_c_up.png" },
    { "gamecube/rt",           "kenney/Nintendo Gamecube/gamecube_trigger_r.png" },
    { "gamecube/south",        "kenney/Nintendo Switch/switch_buttons_down.png" },
    { "gamecube/square",       "kenney/PlayStation Series/playstation_button_color_square.png" },
    { "gamecube/start",        "kenney/Nintendo Gamecube/gamecube_button_start.png" },
    { "gamecube/touch",        "kenney/Nintendo Gamecube/gamecube_button_z.png" },
    { "gamecube/triangle",     "kenney/PlayStation Series/playstation_button_color_triangle.png" },
    { "gamecube/unbound",      "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "gamecube/up",           "kenney/Nintendo Gamecube/gamecube_dpad_up.png" },
    { "gamecube/west",         "kenney/Nintendo Switch/switch_buttons_left.png" },
    { "gamecube/x",            "kenney/Nintendo Gamecube/gamecube_button_x.png" },
    { "gamecube/y",            "kenney/Nintendo Gamecube/gamecube_button_y.png" },
    { "generic/a",             "kenney/Xbox Series/xbox_button_a.png" },
    { "generic/b",             "kenney/Xbox Series/xbox_button_b.png" },
    { "generic/back",          "kenney/Xbox Series/xbox_button_view.png" },
    { "generic/circle",        "kenney/PlayStation Series/playstation_button_color_circle.png" },
    { "generic/cross",         "kenney/PlayStation Series/playstation_button_color_cross.png" },
    { "generic/down",          "kenney/Xbox Series/xbox_dpad_down.png" },
    { "generic/east",          "kenney/Nintendo Switch/switch_buttons_right.png" },
    { "generic/guide",         "kenney/Generic/generic_button_circle.png" },
    { "generic/lb",            "kenney/Xbox Series/xbox_lb.png" },
    { "generic/left",          "kenney/Xbox Series/xbox_dpad_left.png" },
    { "generic/ls",            "kenney/Xbox Series/xbox_ls.png" },
    { "generic/ls_down",       "kenney/Xbox Series/xbox_stick_l_down.png" },
    { "generic/ls_left",       "kenney/Xbox Series/xbox_stick_l_left.png" },
    { "generic/ls_right",      "kenney/Xbox Series/xbox_stick_l_right.png" },
    { "generic/ls_up",         "kenney/Xbox Series/xbox_stick_l_up.png" },
    { "generic/lt",            "kenney/Xbox Series/xbox_lt.png" },
    { "generic/misc1",         "kenney/Xbox Series/xbox_button_share.png" },
    { "generic/misc2",         "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "generic/misc3",         "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "generic/misc4",         "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "generic/misc5",         "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "generic/misc6",         "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "generic/north",         "kenney/Nintendo Switch/switch_buttons_up.png" },
    { "generic/p1",            "kenney/Xbox Series/xbox_elite_paddle_top_right.png" },
    { "generic/p2",            "kenney/Xbox Series/xbox_elite_paddle_top_left.png" },
    { "generic/p3",            "kenney/Xbox Series/xbox_elite_paddle_bottom_right.png" },
    { "generic/p4",            "kenney/Xbox Series/xbox_elite_paddle_bottom_left.png" },
    { "generic/rb",            "kenney/Xbox Series/xbox_rb.png" },
    { "generic/right",         "kenney/Xbox Series/xbox_dpad_right.png" },
    { "generic/rs",            "kenney/Xbox Series/xbox_rs.png" },
    { "generic/rs_down",       "kenney/Xbox Series/xbox_stick_r_down.png" },
    { "generic/rs_left",       "kenney/Xbox Series/xbox_stick_r_left.png" },
    { "generic/rs_right",      "kenney/Xbox Series/xbox_stick_r_right.png" },
    { "generic/rs_up",         "kenney/Xbox Series/xbox_stick_r_up.png" },
    { "generic/rt",            "kenney/Xbox Series/xbox_rt.png" },
    { "generic/south",         "kenney/Nintendo Switch/switch_buttons_down.png" },
    { "generic/square",        "kenney/PlayStation Series/playstation_button_color_square.png" },
    { "generic/start",         "kenney/Xbox Series/xbox_button_menu.png" },
    { "generic/touch",         "kenney/Xbox Series/xbox_button_share.png" },
    { "generic/triangle",      "kenney/PlayStation Series/playstation_button_color_triangle.png" },
    { "generic/unbound",       "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "generic/up",            "kenney/Xbox Series/xbox_dpad_up.png" },
    { "generic/west",          "kenney/Nintendo Switch/switch_buttons_left.png" },
    { "generic/x",             "kenney/Xbox Series/xbox_button_x.png" },
    { "generic/y",             "kenney/Xbox Series/xbox_button_y.png" },
    { "keyboard/100",          "kenney/Keyboard & Mouse/keyboard_d.png" },
    { "keyboard/101",          "kenney/Keyboard & Mouse/keyboard_e.png" },
    { "keyboard/102",          "kenney/Keyboard & Mouse/keyboard_f.png" },
    { "keyboard/103",          "kenney/Keyboard & Mouse/keyboard_g.png" },
    { "keyboard/104",          "kenney/Keyboard & Mouse/keyboard_h.png" },
    { "keyboard/105",          "kenney/Keyboard & Mouse/keyboard_i.png" },
    { "keyboard/106",          "kenney/Keyboard & Mouse/keyboard_j.png" },
    { "keyboard/107",          "kenney/Keyboard & Mouse/keyboard_k.png" },
    { "keyboard/108",          "kenney/Keyboard & Mouse/keyboard_l.png" },
    { "keyboard/109",          "kenney/Keyboard & Mouse/keyboard_m.png" },
    { "keyboard/110",          "kenney/Keyboard & Mouse/keyboard_n.png" },
    { "keyboard/111",          "kenney/Keyboard & Mouse/keyboard_o.png" },
    { "keyboard/112",          "kenney/Keyboard & Mouse/keyboard_p.png" },
    { "keyboard/113",          "kenney/Keyboard & Mouse/keyboard_q.png" },
    { "keyboard/114",          "kenney/Keyboard & Mouse/keyboard_r.png" },
    { "keyboard/115",          "kenney/Keyboard & Mouse/keyboard_s.png" },
    { "keyboard/116",          "kenney/Keyboard & Mouse/keyboard_t.png" },
    { "keyboard/117",          "kenney/Keyboard & Mouse/keyboard_u.png" },
    { "keyboard/118",          "kenney/Keyboard & Mouse/keyboard_v.png" },
    { "keyboard/119",          "kenney/Keyboard & Mouse/keyboard_w.png" },
    { "keyboard/120",          "kenney/Keyboard & Mouse/keyboard_x.png" },
    { "keyboard/121",          "kenney/Keyboard & Mouse/keyboard_y.png" },
    { "keyboard/122",          "kenney/Keyboard & Mouse/keyboard_z.png" },
    { "keyboard/123",          "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "keyboard/124",          "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "keyboard/125",          "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "keyboard/126",          "kenney/Keyboard & Mouse/keyboard_tilde.png" },
    { "keyboard/32",           "kenney/Keyboard & Mouse/keyboard_space_icon.png" },
    { "keyboard/33",           "kenney/Keyboard & Mouse/keyboard_exclamation.png" },
    { "keyboard/34",           "kenney/Keyboard & Mouse/keyboard_quote.png" },
    { "keyboard/35",           "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "keyboard/36",           "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "keyboard/37",           "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "keyboard/38",           "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "keyboard/39",           "kenney/Keyboard & Mouse/keyboard_apostrophe.png" },
    { "keyboard/40",           "kenney/Keyboard & Mouse/keyboard_bracket_open.png" },
    { "keyboard/41",           "kenney/Keyboard & Mouse/keyboard_bracket_close.png" },
    { "keyboard/42",           "kenney/Keyboard & Mouse/keyboard_asterisk.png" },
    { "keyboard/43",           "kenney/Keyboard & Mouse/keyboard_plus.png" },
    { "keyboard/44",           "kenney/Keyboard & Mouse/keyboard_comma.png" },
    { "keyboard/45",           "kenney/Keyboard & Mouse/keyboard_minus.png" },
    { "keyboard/46",           "kenney/Keyboard & Mouse/keyboard_period.png" },
    { "keyboard/47",           "kenney/Keyboard & Mouse/keyboard_slash_forward.png" },
    { "keyboard/48",           "kenney/Keyboard & Mouse/keyboard_0.png" },
    { "keyboard/49",           "kenney/Keyboard & Mouse/keyboard_1.png" },
    { "keyboard/50",           "kenney/Keyboard & Mouse/keyboard_2.png" },
    { "keyboard/51",           "kenney/Keyboard & Mouse/keyboard_3.png" },
    { "keyboard/52",           "kenney/Keyboard & Mouse/keyboard_4.png" },
    { "keyboard/53",           "kenney/Keyboard & Mouse/keyboard_5.png" },
    { "keyboard/54",           "kenney/Keyboard & Mouse/keyboard_6.png" },
    { "keyboard/55",           "kenney/Keyboard & Mouse/keyboard_7.png" },
    { "keyboard/56",           "kenney/Keyboard & Mouse/keyboard_8.png" },
    { "keyboard/57",           "kenney/Keyboard & Mouse/keyboard_9.png" },
    { "keyboard/58",           "kenney/Keyboard & Mouse/keyboard_colon.png" },
    { "keyboard/59",           "kenney/Keyboard & Mouse/keyboard_semicolon.png" },
    { "keyboard/60",           "kenney/Keyboard & Mouse/keyboard_bracket_less.png" },
    { "keyboard/61",           "kenney/Keyboard & Mouse/keyboard_equals.png" },
    { "keyboard/62",           "kenney/Keyboard & Mouse/keyboard_bracket_greater.png" },
    { "keyboard/63",           "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "keyboard/64",           "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "keyboard/65",           "kenney/Keyboard & Mouse/keyboard_a.png" },
    { "keyboard/66",           "kenney/Keyboard & Mouse/keyboard_b.png" },
    { "keyboard/67",           "kenney/Keyboard & Mouse/keyboard_c.png" },
    { "keyboard/68",           "kenney/Keyboard & Mouse/keyboard_d.png" },
    { "keyboard/69",           "kenney/Keyboard & Mouse/keyboard_e.png" },
    { "keyboard/70",           "kenney/Keyboard & Mouse/keyboard_f.png" },
    { "keyboard/71",           "kenney/Keyboard & Mouse/keyboard_g.png" },
    { "keyboard/72",           "kenney/Keyboard & Mouse/keyboard_h.png" },
    { "keyboard/73",           "kenney/Keyboard & Mouse/keyboard_i.png" },
    { "keyboard/74",           "kenney/Keyboard & Mouse/keyboard_j.png" },
    { "keyboard/75",           "kenney/Keyboard & Mouse/keyboard_k.png" },
    { "keyboard/76",           "kenney/Keyboard & Mouse/keyboard_l.png" },
    { "keyboard/77",           "kenney/Keyboard & Mouse/keyboard_m.png" },
    { "keyboard/78",           "kenney/Keyboard & Mouse/keyboard_n.png" },
    { "keyboard/79",           "kenney/Keyboard & Mouse/keyboard_o.png" },
    { "keyboard/80",           "kenney/Keyboard & Mouse/keyboard_p.png" },
    { "keyboard/81",           "kenney/Keyboard & Mouse/keyboard_q.png" },
    { "keyboard/82",           "kenney/Keyboard & Mouse/keyboard_r.png" },
    { "keyboard/83",           "kenney/Keyboard & Mouse/keyboard_s.png" },
    { "keyboard/84",           "kenney/Keyboard & Mouse/keyboard_t.png" },
    { "keyboard/85",           "kenney/Keyboard & Mouse/keyboard_u.png" },
    { "keyboard/86",           "kenney/Keyboard & Mouse/keyboard_v.png" },
    { "keyboard/87",           "kenney/Keyboard & Mouse/keyboard_w.png" },
    { "keyboard/88",           "kenney/Keyboard & Mouse/keyboard_x.png" },
    { "keyboard/89",           "kenney/Keyboard & Mouse/keyboard_y.png" },
    { "keyboard/90",           "kenney/Keyboard & Mouse/keyboard_z.png" },
    { "keyboard/91",           "kenney/Keyboard & Mouse/keyboard_bracket_open.png" },
    { "keyboard/92",           "kenney/Keyboard & Mouse/keyboard_slash_back.png" },
    { "keyboard/93",           "kenney/Keyboard & Mouse/keyboard_bracket_close.png" },
    { "keyboard/94",           "kenney/Keyboard & Mouse/keyboard_caret.png" },
    { "keyboard/95",           "kenney/Keyboard & Mouse/keyboard_underscore.png" },
    { "keyboard/96",           "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "keyboard/97",           "kenney/Keyboard & Mouse/keyboard_a.png" },
    { "keyboard/98",           "kenney/Keyboard & Mouse/keyboard_b.png" },
    { "keyboard/99",           "kenney/Keyboard & Mouse/keyboard_c.png" },
    { "keyboard/Al",           "kenney/Keyboard & Mouse/keyboard_alt.png" },
    { "keyboard/Alt",          "kenney/Keyboard & Mouse/keyboard_alt.png" },
    { "keyboard/BACK",         "kenney/Keyboard & Mouse/keyboard_backspace_icon.png" },
    { "keyboard/Bksp",         "kenney/Keyboard & Mouse/keyboard_backspace.png" },
    { "keyboard/Ct",           "kenney/Keyboard & Mouse/keyboard_ctrl.png" },
    { "keyboard/Ctrl",         "kenney/Keyboard & Mouse/keyboard_ctrl.png" },
    { "keyboard/DOWN",         "kenney/Keyboard & Mouse/keyboard_arrow_down.png" },
    { "keyboard/Enter",        "kenney/Keyboard & Mouse/keyboard_enter.png" },
    { "keyboard/Es",           "kenney/Keyboard & Mouse/keyboard_escape.png" },
    { "keyboard/Esc",          "kenney/Keyboard & Mouse/keyboard_escape.png" },
    { "keyboard/F1",           "kenney/Keyboard & Mouse/keyboard_f1.png" },
    { "keyboard/F10",          "kenney/Keyboard & Mouse/keyboard_f10.png" },
    { "keyboard/F11",          "kenney/Keyboard & Mouse/keyboard_f11.png" },
    { "keyboard/F12",          "kenney/Keyboard & Mouse/keyboard_f12.png" },
    { "keyboard/F2",           "kenney/Keyboard & Mouse/keyboard_f2.png" },
    { "keyboard/F3",           "kenney/Keyboard & Mouse/keyboard_f3.png" },
    { "keyboard/F4",           "kenney/Keyboard & Mouse/keyboard_f4.png" },
    { "keyboard/F5",           "kenney/Keyboard & Mouse/keyboard_f5.png" },
    { "keyboard/F6",           "kenney/Keyboard & Mouse/keyboard_f6.png" },
    { "keyboard/F7",           "kenney/Keyboard & Mouse/keyboard_f7.png" },
    { "keyboard/F8",           "kenney/Keyboard & Mouse/keyboard_f8.png" },
    { "keyboard/F9",           "kenney/Keyboard & Mouse/keyboard_f9.png" },
    { "keyboard/K0",           "kenney/Keyboard & Mouse/keyboard_0.png" },
    { "keyboard/K1",           "kenney/Keyboard & Mouse/keyboard_1.png" },
    { "keyboard/K2",           "kenney/Keyboard & Mouse/keyboard_2.png" },
    { "keyboard/K3",           "kenney/Keyboard & Mouse/keyboard_3.png" },
    { "keyboard/K4",           "kenney/Keyboard & Mouse/keyboard_4.png" },
    { "keyboard/K5",           "kenney/Keyboard & Mouse/keyboard_5.png" },
    { "keyboard/K6",           "kenney/Keyboard & Mouse/keyboard_6.png" },
    { "keyboard/K7",           "kenney/Keyboard & Mouse/keyboard_7.png" },
    { "keyboard/K8",           "kenney/Keyboard & Mouse/keyboard_8.png" },
    { "keyboard/K9",           "kenney/Keyboard & Mouse/keyboard_9.png" },
    { "keyboard/LEFT",         "kenney/Keyboard & Mouse/keyboard_arrow_left.png" },
    { "keyboard/Num0",         "kenney/Keyboard & Mouse/keyboard_0.png" },
    { "keyboard/Num1",         "kenney/Keyboard & Mouse/keyboard_1.png" },
    { "keyboard/Num2",         "kenney/Keyboard & Mouse/keyboard_2.png" },
    { "keyboard/Num3",         "kenney/Keyboard & Mouse/keyboard_3.png" },
    { "keyboard/Num4",         "kenney/Keyboard & Mouse/keyboard_4.png" },
    { "keyboard/Num5",         "kenney/Keyboard & Mouse/keyboard_5.png" },
    { "keyboard/Num6",         "kenney/Keyboard & Mouse/keyboard_6.png" },
    { "keyboard/Num7",         "kenney/Keyboard & Mouse/keyboard_7.png" },
    { "keyboard/Num8",         "kenney/Keyboard & Mouse/keyboard_8.png" },
    { "keyboard/Num9",         "kenney/Keyboard & Mouse/keyboard_9.png" },
    { "keyboard/RETURN",       "kenney/Keyboard & Mouse/keyboard_return.png" },
    { "keyboard/RIGHT",        "kenney/Keyboard & Mouse/keyboard_arrow_right.png" },
    { "keyboard/SHIFT",        "kenney/Keyboard & Mouse/keyboard_shift_icon.png" },
    { "keyboard/Shift",        "kenney/Keyboard & Mouse/keyboard_shift.png" },
    { "keyboard/Space",        "kenney/Keyboard & Mouse/keyboard_space.png" },
    { "keyboard/TAB",          "kenney/Keyboard & Mouse/keyboard_tab_icon.png" },
    { "keyboard/Tab",          "kenney/Keyboard & Mouse/keyboard_tab.png" },
    { "keyboard/UP",           "kenney/Keyboard & Mouse/keyboard_arrow_up.png" },
    { "nintendo/a",            "kenney/Nintendo Switch/switch_button_a.png" },
    { "nintendo/b",            "kenney/Nintendo Switch/switch_button_b.png" },
    { "nintendo/back",         "kenney/Nintendo Switch/switch_button_minus.png" },
    { "nintendo/circle",       "kenney/PlayStation Series/playstation_button_color_circle.png" },
    { "nintendo/cross",        "kenney/PlayStation Series/playstation_button_color_cross.png" },
    { "nintendo/down",         "kenney/Nintendo Switch/switch_dpad_down.png" },
    { "nintendo/east",         "kenney/Nintendo Switch/switch_buttons_right.png" },
    { "nintendo/guide",        "kenney/Generic/generic_button_circle.png" },
    { "nintendo/lb",           "kenney/Nintendo Switch/switch_button_l.png" },
    { "nintendo/left",         "kenney/Nintendo Switch/switch_dpad_left.png" },
    { "nintendo/ls",           "kenney/Nintendo Switch/switch_stick_l_press.png" },
    { "nintendo/ls_down",      "kenney/Nintendo Switch/switch_stick_l_down.png" },
    { "nintendo/ls_left",      "kenney/Nintendo Switch/switch_stick_l_left.png" },
    { "nintendo/ls_right",     "kenney/Nintendo Switch/switch_stick_l_right.png" },
    { "nintendo/ls_up",        "kenney/Nintendo Switch/switch_stick_l_up.png" },
    { "nintendo/lt",           "kenney/Nintendo Switch/switch_button_zl.png" },
    { "nintendo/misc1",        "kenney/Nintendo Switch/switch_button_sync.png" },
    { "nintendo/misc2",        "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "nintendo/misc3",        "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "nintendo/misc4",        "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "nintendo/misc5",        "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "nintendo/misc6",        "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "nintendo/north",        "kenney/Nintendo Switch/switch_buttons_up.png" },
    { "nintendo/p1",           "kenney/Xbox Series/xbox_elite_paddle_top_right.png" },
    { "nintendo/p2",           "kenney/Xbox Series/xbox_elite_paddle_top_left.png" },
    { "nintendo/p3",           "kenney/Xbox Series/xbox_elite_paddle_bottom_right.png" },
    { "nintendo/p4",           "kenney/Xbox Series/xbox_elite_paddle_bottom_left.png" },
    { "nintendo/rb",           "kenney/Nintendo Switch/switch_button_r.png" },
    { "nintendo/right",        "kenney/Nintendo Switch/switch_dpad_right.png" },
    { "nintendo/rs",           "kenney/Nintendo Switch/switch_stick_r_press.png" },
    { "nintendo/rs_down",      "kenney/Nintendo Switch/switch_stick_r_down.png" },
    { "nintendo/rs_left",      "kenney/Nintendo Switch/switch_stick_r_left.png" },
    { "nintendo/rs_right",     "kenney/Nintendo Switch/switch_stick_r_right.png" },
    { "nintendo/rs_up",        "kenney/Nintendo Switch/switch_stick_r_up.png" },
    { "nintendo/rt",           "kenney/Nintendo Switch/switch_button_zr.png" },
    { "nintendo/south",        "kenney/Nintendo Switch/switch_buttons_down.png" },
    { "nintendo/square",       "kenney/PlayStation Series/playstation_button_color_square.png" },
    { "nintendo/start",        "kenney/Nintendo Switch/switch_button_plus.png" },
    { "nintendo/touch",        "kenney/Nintendo Switch/switch_button_sync.png" },
    { "nintendo/triangle",     "kenney/PlayStation Series/playstation_button_color_triangle.png" },
    { "nintendo/unbound",      "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "nintendo/up",           "kenney/Nintendo Switch/switch_dpad_up.png" },
    { "nintendo/west",         "kenney/Nintendo Switch/switch_buttons_left.png" },
    { "nintendo/x",            "kenney/Nintendo Switch/switch_button_x.png" },
    { "nintendo/y",            "kenney/Nintendo Switch/switch_button_y.png" },
    { "playstation/a",         "kenney/PlayStation Series/playstation_button_color_cross.png" },
    { "playstation/b",         "kenney/PlayStation Series/playstation_button_color_circle.png" },
    { "playstation/back",      "kenney/PlayStation Series/playstation5_button_create.png" },
    { "playstation/circle",    "kenney/PlayStation Series/playstation_button_color_circle.png" },
    { "playstation/cross",     "kenney/PlayStation Series/playstation_button_color_cross.png" },
    { "playstation/down",      "kenney/PlayStation Series/playstation_dpad_down.png" },
    { "playstation/east",      "kenney/Nintendo Switch/switch_buttons_right.png" },
    { "playstation/guide",     "kenney/Generic/generic_button_circle.png" },
    { "playstation/lb",        "kenney/PlayStation Series/playstation_trigger_l1.png" },
    { "playstation/left",      "kenney/PlayStation Series/playstation_dpad_left.png" },
    { "playstation/ls",        "kenney/PlayStation Series/playstation_button_l3.png" },
    { "playstation/ls_down",   "kenney/PlayStation Series/playstation_stick_l_down.png" },
    { "playstation/ls_left",   "kenney/PlayStation Series/playstation_stick_l_left.png" },
    { "playstation/ls_right",  "kenney/PlayStation Series/playstation_stick_l_right.png" },
    { "playstation/ls_up",     "kenney/PlayStation Series/playstation_stick_l_up.png" },
    { "playstation/lt",        "kenney/PlayStation Series/playstation_trigger_l2.png" },
    { "playstation/misc1",     "kenney/PlayStation Series/playstation5_button_create.png" },
    { "playstation/misc2",     "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "playstation/misc3",     "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "playstation/misc4",     "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "playstation/misc5",     "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "playstation/misc6",     "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "playstation/north",     "kenney/Nintendo Switch/switch_buttons_up.png" },
    { "playstation/p1",        "kenney/Xbox Series/xbox_elite_paddle_top_right.png" },
    { "playstation/p2",        "kenney/Xbox Series/xbox_elite_paddle_top_left.png" },
    { "playstation/p3",        "kenney/Xbox Series/xbox_elite_paddle_bottom_right.png" },
    { "playstation/p4",        "kenney/Xbox Series/xbox_elite_paddle_bottom_left.png" },
    { "playstation/rb",        "kenney/PlayStation Series/playstation_trigger_r1.png" },
    { "playstation/right",     "kenney/PlayStation Series/playstation_dpad_right.png" },
    { "playstation/rs",        "kenney/PlayStation Series/playstation_button_r3.png" },
    { "playstation/rs_down",   "kenney/PlayStation Series/playstation_stick_r_down.png" },
    { "playstation/rs_left",   "kenney/PlayStation Series/playstation_stick_r_left.png" },
    { "playstation/rs_right",  "kenney/PlayStation Series/playstation_stick_r_right.png" },
    { "playstation/rs_up",     "kenney/PlayStation Series/playstation_stick_r_up.png" },
    { "playstation/rt",        "kenney/PlayStation Series/playstation_trigger_r2.png" },
    { "playstation/south",     "kenney/Nintendo Switch/switch_buttons_down.png" },
    { "playstation/square",    "kenney/PlayStation Series/playstation_button_color_square.png" },
    { "playstation/start",     "kenney/PlayStation Series/playstation5_button_options.png" },
    { "playstation/touch",     "kenney/PlayStation Series/playstation5_touchpad.png" },
    { "playstation/triangle",  "kenney/PlayStation Series/playstation_button_color_triangle.png" },
    { "playstation/unbound",   "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "playstation/up",        "kenney/PlayStation Series/playstation_dpad_up.png" },
    { "playstation/west",      "kenney/Nintendo Switch/switch_buttons_left.png" },
    { "playstation/x",         "kenney/PlayStation Series/playstation_button_color_square.png" },
    { "playstation/y",         "kenney/PlayStation Series/playstation_button_color_triangle.png" },
    { "steamdeck/a",           "kenney/Steam Deck/steamdeck_button_a.png" },
    { "steamdeck/b",           "kenney/Steam Deck/steamdeck_button_b.png" },
    { "steamdeck/back",        "kenney/Steam Deck/steamdeck_button_view.png" },
    { "steamdeck/circle",      "kenney/PlayStation Series/playstation_button_color_circle.png" },
    { "steamdeck/cross",       "kenney/PlayStation Series/playstation_button_color_cross.png" },
    { "steamdeck/down",        "kenney/Steam Deck/steamdeck_dpad_down.png" },
    { "steamdeck/east",        "kenney/Nintendo Switch/switch_buttons_right.png" },
    { "steamdeck/guide",       "kenney/Steam Deck/steamdeck_button_guide.png" },
    { "steamdeck/lb",          "kenney/Steam Deck/steamdeck_button_l1.png" },
    { "steamdeck/left",        "kenney/Steam Deck/steamdeck_dpad_left.png" },
    { "steamdeck/ls",          "kenney/Steam Deck/steamdeck_stick_l_press.png" },
    { "steamdeck/ls_down",     "kenney/Steam Deck/steamdeck_stick_l_down.png" },
    { "steamdeck/ls_left",     "kenney/Steam Deck/steamdeck_stick_l_left.png" },
    { "steamdeck/ls_right",    "kenney/Steam Deck/steamdeck_stick_l_right.png" },
    { "steamdeck/ls_up",       "kenney/Steam Deck/steamdeck_stick_l_up.png" },
    { "steamdeck/lt",          "kenney/Steam Deck/steamdeck_button_l2.png" },
    { "steamdeck/misc1",       "kenney/Steam Deck/steamdeck_button_quickaccess.png" },
    { "steamdeck/misc2",       "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "steamdeck/misc3",       "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "steamdeck/misc4",       "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "steamdeck/misc5",       "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "steamdeck/misc6",       "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "steamdeck/north",       "kenney/Nintendo Switch/switch_buttons_up.png" },
    { "steamdeck/p1",          "kenney/Steam Deck/steamdeck_button_r4.png" },
    { "steamdeck/p2",          "kenney/Steam Deck/steamdeck_button_l4.png" },
    { "steamdeck/p3",          "kenney/Steam Deck/steamdeck_button_r5.png" },
    { "steamdeck/p4",          "kenney/Steam Deck/steamdeck_button_l5.png" },
    { "steamdeck/rb",          "kenney/Steam Deck/steamdeck_button_r1.png" },
    { "steamdeck/right",       "kenney/Steam Deck/steamdeck_dpad_right.png" },
    { "steamdeck/rs",          "kenney/Steam Deck/steamdeck_stick_r_press.png" },
    { "steamdeck/rs_down",     "kenney/Steam Deck/steamdeck_stick_r_down.png" },
    { "steamdeck/rs_left",     "kenney/Steam Deck/steamdeck_stick_r_left.png" },
    { "steamdeck/rs_right",    "kenney/Steam Deck/steamdeck_stick_r_right.png" },
    { "steamdeck/rs_up",       "kenney/Steam Deck/steamdeck_stick_r_up.png" },
    { "steamdeck/rt",          "kenney/Steam Deck/steamdeck_button_r2.png" },
    { "steamdeck/south",       "kenney/Nintendo Switch/switch_buttons_down.png" },
    { "steamdeck/square",      "kenney/PlayStation Series/playstation_button_color_square.png" },
    { "steamdeck/start",       "kenney/Steam Deck/steamdeck_button_options.png" },
    { "steamdeck/touch",       "kenney/Steam Deck/steamdeck_trackpad.png" },
    { "steamdeck/triangle",    "kenney/PlayStation Series/playstation_button_color_triangle.png" },
    { "steamdeck/unbound",     "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "steamdeck/up",          "kenney/Steam Deck/steamdeck_dpad_up.png" },
    { "steamdeck/west",        "kenney/Nintendo Switch/switch_buttons_left.png" },
    { "steamdeck/x",           "kenney/Steam Deck/steamdeck_button_x.png" },
    { "steamdeck/y",           "kenney/Steam Deck/steamdeck_button_y.png" },
    { "xbox/a",                "kenney/Xbox Series/xbox_button_color_a.png" },
    { "xbox/b",                "kenney/Xbox Series/xbox_button_color_b.png" },
    { "xbox/back",             "kenney/Xbox Series/xbox_button_view.png" },
    { "xbox/circle",           "kenney/PlayStation Series/playstation_button_color_circle.png" },
    { "xbox/cross",            "kenney/PlayStation Series/playstation_button_color_cross.png" },
    { "xbox/down",             "kenney/Xbox Series/xbox_dpad_down.png" },
    { "xbox/east",             "kenney/Nintendo Switch/switch_buttons_right.png" },
    { "xbox/guide",            "kenney/Generic/generic_button_circle.png" },
    { "xbox/lb",               "kenney/Xbox Series/xbox_lb.png" },
    { "xbox/left",             "kenney/Xbox Series/xbox_dpad_left.png" },
    { "xbox/ls",               "kenney/Xbox Series/xbox_ls.png" },
    { "xbox/ls_down",          "kenney/Xbox Series/xbox_stick_l_down.png" },
    { "xbox/ls_left",          "kenney/Xbox Series/xbox_stick_l_left.png" },
    { "xbox/ls_right",         "kenney/Xbox Series/xbox_stick_l_right.png" },
    { "xbox/ls_up",            "kenney/Xbox Series/xbox_stick_l_up.png" },
    { "xbox/lt",               "kenney/Xbox Series/xbox_lt.png" },
    { "xbox/misc1",            "kenney/Xbox Series/xbox_button_share.png" },
    { "xbox/misc2",            "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "xbox/misc3",            "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "xbox/misc4",            "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "xbox/misc5",            "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "xbox/misc6",            "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "xbox/north",            "kenney/Nintendo Switch/switch_buttons_up.png" },
    { "xbox/p1",               "kenney/Xbox Series/xbox_elite_paddle_top_right.png" },
    { "xbox/p2",               "kenney/Xbox Series/xbox_elite_paddle_top_left.png" },
    { "xbox/p3",               "kenney/Xbox Series/xbox_elite_paddle_bottom_right.png" },
    { "xbox/p4",               "kenney/Xbox Series/xbox_elite_paddle_bottom_left.png" },
    { "xbox/rb",               "kenney/Xbox Series/xbox_rb.png" },
    { "xbox/right",            "kenney/Xbox Series/xbox_dpad_right.png" },
    { "xbox/rs",               "kenney/Xbox Series/xbox_rs.png" },
    { "xbox/rs_down",          "kenney/Xbox Series/xbox_stick_r_down.png" },
    { "xbox/rs_left",          "kenney/Xbox Series/xbox_stick_r_left.png" },
    { "xbox/rs_right",         "kenney/Xbox Series/xbox_stick_r_right.png" },
    { "xbox/rs_up",            "kenney/Xbox Series/xbox_stick_r_up.png" },
    { "xbox/rt",               "kenney/Xbox Series/xbox_rt.png" },
    { "xbox/south",            "kenney/Nintendo Switch/switch_buttons_down.png" },
    { "xbox/square",           "kenney/PlayStation Series/playstation_button_color_square.png" },
    { "xbox/start",            "kenney/Xbox Series/xbox_button_menu.png" },
    { "xbox/touch",            "kenney/Xbox Series/xbox_button_share.png" },
    { "xbox/triangle",         "kenney/PlayStation Series/playstation_button_color_triangle.png" },
    { "xbox/unbound",          "kenney/Keyboard & Mouse/keyboard_question.png" },
    { "xbox/up",               "kenney/Xbox Series/xbox_dpad_up.png" },
    { "xbox/west",             "kenney/Nintendo Switch/switch_buttons_left.png" },
    { "xbox/x",                "kenney/Xbox Series/xbox_button_color_x.png" },
    { "xbox/y",                "kenney/Xbox Series/xbox_button_color_y.png" },
};
// clang-format on

}   // namespace prompt_art

#endif // PORT_PROMPT_ART_H
