VITASDK ?= /usr/local/vitasdk
BUILD_DIR ?= build-vita
CMAKE ?= cmake
JOBS ?= 8

.PHONY: all configure build vpk clean

all: vpk

configure:
	$(CMAKE) -S . -B $(BUILD_DIR) -G "Unix Makefiles" \
		-DCMAKE_TOOLCHAIN_FILE=$(VITASDK)/share/vita.toolchain.cmake \
		-DCMAKE_BUILD_TYPE=Release \
		-DSTRIKERS_AURORA=ON \
		-DSTRIKERS_FFMPEG=OFF \
		-DCMAKE_PREFIX_PATH=$(VITASDK)/arm-vita-eabi

build: configure
	$(CMAKE) --build $(BUILD_DIR) --target strikers -j$(JOBS)

vpk: configure
	$(CMAKE) --build $(BUILD_DIR) --target strikers_vita.vpk-vpk -j$(JOBS)

clean:
	$(CMAKE) -E rm -rf $(BUILD_DIR)
